["refractiveindex.info"]
git-tree-sha1 = "e9f3783374aecc0f476b0bf213c3da7207b935a2"

    [["refractiveindex.info".download]]
    sha256 = "a1737d1c201ec9e10efc44f9a823ac4d67cf1f670179be190bf2a90ecf73605c"
    url = "https://github.com/polyanskiy/refractiveindex.info-database/archive/v2022-10-01.tar.gz"
