["refractiveindex.info"]
git-tree-sha1 = "cf11d0819852909dd09a8a3f3e7f40a819d8ea61"

    [["refractiveindex.info".download]]
    sha256 = "3e1bccbaba3930d99912f90e2c6d1e0c47912e52ae884c5f171e82bbda4a9c9b"
    url = "https://github.com/polyanskiy/refractiveindex.info-database/archive/v2023-10-04.tar.gz"
