["refractiveindex.info"]
git-tree-sha1 = "4804d1ffb1575407b24dbbe3a6e375c693c2ceec"

    [["refractiveindex.info".download]]
    sha256 = "914b5a04f945ba986dad350a2f161af3228a372d52eec60ea38c024bfbd48983"
    url = "https://github.com/polyanskiy/refractiveindex.info-database/archive/v2024-12-31.tar.gz"
